#Numpy-Pandas-Matplotlib-Seaborn  

## Numpy

In [1]:
import numpy as np

In [2]:
a=[1,3,5,"fatih","sueda",2j+5,3.5]

In [3]:
a=[1,3,5,7,9]
b=[2,4,6,8,10]

In [5]:
type(a)

list

In [8]:
ab=[]
for i in range(len(a)):
  ab.append(a[i]*b[i])

ab

[2, 12, 30, 56, 90]

In [9]:
x=np.array([1,3,5,7,9])
y=np.array(b)

In [10]:
x*y

array([ 2, 12, 30, 56, 90])

In [ ]:
#0 > siyah
#1> beyaz

In [12]:
sifirlar=np.zeros(10,dtype=int)
sifirlar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
birler=np.ones(10,dtype=int)
birler

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.random.randint(5)

4

In [22]:
np.random.randint(72,81)

77

In [23]:
np.random.randint(1,81,100)

array([12, 62, 18, 37, 14, 68, 48, 73, 64,  2, 11, 38, 57, 75, 17,  1, 79,
       41,  2, 57, 59, 13, 45, 63, 68, 68, 74, 63, 54, 74, 25,  6, 25, 67,
        9, 25, 19, 23, 41, 22,  6, 22, 70, 71,  4, 12, 32, 21, 77, 79, 39,
       35, 73, 62,  9, 48, 63, 61, 18,  4, 39, 78, 62, 12, 60, 69, 32, 46,
       27, 34, 12, 32, 22, 44, 20,  4, 11, 17, 15, 28, 79, 55, 73, 28, 25,
       29, 36, 37, 16, 25, 56, 73, 27, 47, 39,  1, 74, 56, 39, 77])

In [26]:
b=np.random.normal(10,4,(3,4))
b
# (3,4) MxN

array([[ 8.53023242, 11.21231296, 11.4152028 ,  6.47165557],
       [ 6.0367405 , 11.84628021,  8.38427478, 11.88785507],
       [ 9.04096427,  4.57797583,  8.41779199, -0.07240262]])

In [27]:
b.dtype

dtype('float64')

In [29]:
c=np.random.randint(1,81,(3,3))
c

array([[32, 72, 79],
       [69, 16, 42],
       [37, 45, 12]])

In [30]:
c.ndim

2

In [31]:
c.shape

(3, 3)

In [32]:
c.dtype

dtype('int64')

In [33]:
a=["mehmet"]
a

['mehmet']

In [36]:
a[0]

'mehmet'

In [34]:
type(a)

list

In [35]:
type(a[0])

str

In [38]:
c=np.random.randint(1,5,size=(18))
c

array([2, 2, 1, 4, 4, 3, 4, 4, 1, 1, 1, 2, 1, 2, 4, 3, 4, 4])

In [40]:
c.reshape(6,3)

array([[2, 2, 1],
       [4, 4, 3],
       [4, 4, 1],
       [1, 1, 2],
       [1, 2, 4],
       [3, 4, 4]])

In [41]:
c.reshape(-1,6)

array([[2, 2, 1, 4, 4, 3],
       [4, 4, 1, 1, 1, 2],
       [1, 2, 4, 3, 4, 4]])

In [42]:
c.reshape(6,-1)

array([[2, 2, 1],
       [4, 4, 3],
       [4, 4, 1],
       [1, 1, 2],
       [1, 2, 4],
       [3, 4, 4]])

In [44]:
x=np.random.randint(100,size=10)
x

array([31, 84, 61, 86, 35, 95, 97, 96, 33, 14])

In [46]:
x[2]

61

In [48]:
x[-2]

33

In [49]:
s="aliahmet"

In [50]:
s[2]

'i'

In [51]:
s[::]

'aliahmet'

In [52]:
s[:3]

'ali'

In [53]:
s[::-1]

'temhaila'

In [55]:
m=np.random.randint(10,size=(3,5))
m

array([[8, 7, 3, 4, 6],
       [3, 8, 3, 9, 3],
       [8, 1, 2, 6, 6]])

In [56]:
m[2,3]

6

In [57]:
m[1,3]

9

In [58]:
m[1,3]=72

In [59]:
m

array([[ 8,  7,  3,  4,  6],
       [ 3,  8,  3, 72,  3],
       [ 8,  1,  2,  6,  6]])

In [60]:
m[:2,:]

array([[ 8,  7,  3,  4,  6],
       [ 3,  8,  3, 72,  3]])

In [61]:
m[1:,3:]#72-3

array([[72,  3],
       [ 6,  6]])

In [64]:
x=np.arange(0,50,5)
x

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [67]:
#fancy index
a=[0,2,4]
x[a]

array([ 0, 10, 20])

In [69]:
y=np.array(range(21))
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
for i in y:
  if i <10:
    print(i)

In [71]:
y<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False])

In [72]:
y[True]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20]])

In [73]:
y[y<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
y[y>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [75]:
y**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400])

In [76]:
y-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19])

In [77]:
y.sum()

210

In [78]:
y.mean()

10.0

In [80]:
y.max()

20

In [81]:
y.min()

0

In [ ]:
# 5x1+3x2=72
# 3x1+9x2=81

In [84]:
a=np.array([[5,3],[3,9]])
b=np.array([72,81])

In [85]:
a

array([[5, 3],
       [3, 9]])

In [86]:
b

array([72, 81])

In [87]:
xs=np.linalg.solve(a,b)
xs

array([11.25,  5.25])

In [88]:
x1,x2=xs

In [89]:
x1

11.25

In [90]:
x2

5.25