In [1]:
import time
import numpy as np

In [3]:
start_time = time.time()

a = np.arange(1000000)
a ** 2
time_1 = time.time() - start_time

start_time_2 = time.time()

b = range(1000000)
[i ** 2 for i in b]
time_2 = time.time() - start_time_2

print(time_2 / time_1)

# Arraylerin listelerden kaç kat daha hızlı olduğunu buradan görebilirsiniz.
# Arraylerin daha hızlı olmasının sebebi numpy'ın vektörleşmeyi desteklemesidir.

21.999761802677337


In [4]:
import numpy as np

# Ndarray oluşturmak için birinci yöntem

x = np.array([4,5,6,7])
print(x)

[4 5 6 7]


In [12]:
print(type(x))

# class ismini öğrendik

<class 'numpy.ndarray'>


In [7]:
print(x.shape)

# 4 elemanlı olduğu için böyle bir tuple değeri aldık

(4,)


In [8]:
print(x.size)

# Ndarrayımızın oluşturduğu toplam eleman sayısını verir.

4


In [9]:
print(x.ndim)

# Ndarrayimizin kaç boyutlu olduğunu söyler. Bu ndarray 1-D.(bir boyutlu)

1


In [10]:
print(x.nbytes)

# Depolamak için gerekli byte'ı gösterir.

16


In [11]:
print(x.dtype)

# Ndarray'e ait elemanların veri tipini gösterir.

int32


In [15]:
# 2 Boyutlu Ndarray oluşturmak(2-D)

y = np.array([[1,2,3],[4,5,6]])

print(y)

# Matris görünümlü bir array aldık.

[[1 2 3]
 [4 5 6]]


In [16]:
print(type(y))

# classı değişmedi.

<class 'numpy.ndarray'>


In [17]:
print(y.shape)

# Her eksende bize sayıları verdi. 2 satırları, 3 sütunları belirtti.

(2, 3)


In [18]:
print(y.size)

# Eleman sayısını verdi.

6


In [19]:
print(y.ndim)

# Kaç boyutlu olduğunu gösterdi

2


In [20]:
print(y.nbytes)

# Kaç byte yer kapladığını gösterdi.

24


In [21]:
print(y.dtype)

# Ndarray'ın elemanlarının veri tipini gösterdi.

int32


In [28]:
# 3 Boyutlu Ndarray Olusturmak

z = np.array([[[1,2],[3,4]],[[1,2],[3,4]]])

print(z)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [29]:
print(z.shape)

# 2 adet 2 satır 2 sütunlu matrislerden olustuğunu gösterir.

(2, 2, 2)


In [24]:
print(z.ndim)

# Boyut sayısını gösterdi.

3


In [31]:
x = np.array([1,2,3])

print(x)
print(x.dtype)

[1 2 3]
int32


In [32]:
y = np.array([1,"2",3])

print(y)
print(y.dtype)

# Ndarray veri tipleri her zaman aynı olmalıdır.
# u11 unicode değerli bir string değeri burada tanımladı.

['1' '2' '3']
<U11


In [33]:
z = np.array([1,2.0,3])

print(z)
print(z.dtype)

# Ndarray bu seferde aynı tipte olması için bütün elemanların veri tipini float64'e çevirdi.
# Bu duruma upcasting deniyor. İnternetten araştırma yaparakta detaylı bilgiye ulaşabilirsiniz.

[1. 2. 3.]
float64
