In [1]:
import numpy as np

# np.arange()

x = np.arange(10)

print(x)

# 0'dan 10'a kadar olan sayılarla 1-D bir array oluşturdu.

[0 1 2 3 4 5 6 7 8 9]


In [2]:
x = np.arange(5)

print(x)

[0 1 2 3 4]


In [5]:
y = np.arange(4, 9)

print(y)

# 2. parametre ile aralığı kendimiz belirleyebiliyoruz.
# 4'ten 9'a kadar olan sayılardan 1-D array oluşturduk.

[4 5 6 7 8]


In [7]:
z = np.arange(3, 23, 4)

print(z)

# 3. parametre ile aralıktaki sayıların kaçar kaçar artarak array'e ekleneceğini belirleyebiliyoruz.
# 3'ten 23'e kadar 4'er 4'er artarak ilerleyen 1-D array oluşturduk.

[ 3  7 11 15 19]


In [8]:
# np.linspace()

x = np.linspace(0, 15, 10)

print(x)

# 0'dan 15'e kadar olan sayılardan 10 tanesiyle array oluşturduk.
# Bu metotta 15'te dahildir.

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.         11.66666667 13.33333333 15.        ]


In [9]:
x = np.linspace(0, 15)

print(x)

# Eğer 3. parametreyi girmezsek varsayılan=50 eleman olarak girilir ve 50 elemanlı array oluşturur.

[ 0.          0.30612245  0.6122449   0.91836735  1.2244898   1.53061224
  1.83673469  2.14285714  2.44897959  2.75510204  3.06122449  3.36734694
  3.67346939  3.97959184  4.28571429  4.59183673  4.89795918  5.20408163
  5.51020408  5.81632653  6.12244898  6.42857143  6.73469388  7.04081633
  7.34693878  7.65306122  7.95918367  8.26530612  8.57142857  8.87755102
  9.18367347  9.48979592  9.79591837 10.10204082 10.40816327 10.71428571
 11.02040816 11.32653061 11.63265306 11.93877551 12.24489796 12.55102041
 12.85714286 13.16326531 13.46938776 13.7755102  14.08163265 14.3877551
 14.69387755 15.        ]


In [10]:
x = np.linspace(0, 15, endpoint= False)

print(x)

# endpoint= False parametresiyle istersek bitiş noktasını yani 15'i dahil etmeyebiliriz.

[ 0.   0.3  0.6  0.9  1.2  1.5  1.8  2.1  2.4  2.7  3.   3.3  3.6  3.9
  4.2  4.5  4.8  5.1  5.4  5.7  6.   6.3  6.6  6.9  7.2  7.5  7.8  8.1
  8.4  8.7  9.   9.3  9.6  9.9 10.2 10.5 10.8 11.1 11.4 11.7 12.  12.3
 12.6 12.9 13.2 13.5 13.8 14.1 14.4 14.7]


In [12]:
# np.reshape()

x = np.arange(20)

print(x)
print()

y = np.reshape(x, (4, 5))

print(y)

# Matrise reshape ile yeniden şekil verebiliyoruz.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [13]:
x = np.arange(20)

print(x)
print()

y = np.reshape(x, (5, 5))

print(y)

# Hata alırız çünkü ilk matristeki eleman sayısı ile dönüştürmek istediğimiz matristeki eleman sayısı eşit olmalı.
# 5*5 25 elemanlı matris oluşturmak istiyoruz. Ancak elimizde 20 eleman var. Bu yüzden hata aldık.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]



ValueError: cannot reshape array of size 20 into shape (5,5)

In [14]:
x = np.arange(32)

print(x)
print()

y = np.reshape(x, (2, 4, 4))

print(y)

# 3 parametreli şekilde böyle kullanabiliyoruz ve bu da bize 3 boyutlu bir matris veriyor.
# (2, 4, 4) = 2 tane 4*4lük matris oluşturduk.

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


In [15]:
x = np.linspace(0, 19, 20)

print(x)
print()

y = np.reshape(x, (2, 10))

print(y)

# Şekillendirmeyi linspace'tende uygulayabiliriz.

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


In [16]:
z = np.linspace(0, 19, 20).reshape(2, 10)

print(z)

# Fonksiyonları bu şekilde art arda da sıralayabiliriz.

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


In [17]:
# random.random()

x = np.random.random((2, 3))

print(x)

# 0'dan 1 'e kadar olan sayılardan random olarak matris oluşturur.

[[0.75493123 0.81401898 0.23608946]
 [0.35471544 0.61081078 0.38280192]]


In [18]:
# random.randint()

x = np.random.randint(3, 12, size= (3, 2))

print(x)

# Belirtilen aralıkta belirtilen değerlerde random sayılarla matris oluşturur.
# Sadece int sayıları alır.
# (3, 12, size= (3, 2)) = 3'ten 12'ye kadar 3*2'lik random int sayılarla matris oluşturur.

[[ 7  8]
 [ 6 11]
 [ 6 11]]
