In [1]:
import numpy as np

In [2]:
# element - wise, array - wise

x = np.random.randint(1, 10, size= 5)

print(x)

[1 1 8 2 9]


In [3]:
y = np.random.randint(1, 10, size= 5)

print(y)

[6 4 4 8 4]


In [4]:
print(x + y)
print(np.add(x, y))

# İki şekilde de toplama işlemi yapılabiliyor.
# Toplama işlemi aynı index numarasına sahip olanlar arasında yapılıyor.

[ 7  5 12 10 13]
[ 7  5 12 10 13]


In [5]:
print(type(x + y))
print(type(np.add(x, y)))

# Her iki toplama işleminde de sonuç olarak yine bir ndarray çıktısı alırız.

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
print(x - y)
print(np.subtract(x, y))

# Çıkarma işlemi için böyle kullanıyoruz.

[-5 -3  4 -6  5]
[-5 -3  4 -6  5]


In [7]:
print(x * y)
print(np.multiply(x, y))

# Çarpma işleminde bunları kullanıyoruz.

[ 6  4 32 16 36]
[ 6  4 32 16 36]


In [8]:
print(x / y)
print(np.divide(x, y))

# Bölme işleminde bunları kullanıyoruz.

[0.16666667 0.25       2.         0.25       2.25      ]
[0.16666667 0.25       2.         0.25       2.25      ]


In [9]:
print(x + 3)
print(x - 3)
print(x * 3)
print(x / 3)

# Sabit bir sayıyla işleme soktuğumuzda bütün elemanlar tek tek aynı sabit sayıyla işleme girerler.

[ 4  4 11  5 12]
[-2 -2  5 -1  6]
[ 3  3 24  6 27]
[0.33333333 0.33333333 2.66666667 0.66666667 3.        ]


In [10]:
print(x == y)

# x'in ve y'nin elemanlarının birbirine eşit olup olmadığını sorguladık.

[False False False False False]


In [11]:
y = np.random.randint(1, 10, size= 6)

print(y)

[3 7 2 6 2 4]


In [12]:
print(x == y)

# Eğer eleman sayıları aynı değilse bu şekilde hata alırız.

False


C:\Users\Fallrytme\AppData\Local\Temp\ipykernel_10340\1734864879.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(x == y)


In [13]:
print(x + y)

# Aynı şekilde işleme sokarsakta hata alırız. 
# Broadcasting konusunu daha sonra göstereceğim.

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [14]:
print(np.array_equal(x, y))

# x ve y'nin eşitliğini sorguladık ve False cevabı aldık.

False


In [18]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
c = np.array([1, 2, 4])

print(np.array_equal(a, b))
print(np.array_equal(a, c))

# Tek bir False değer onların eşit olmadığını gösterir. Buradan da onun kanıtını gördük.

True
False


In [19]:
print(np.sqrt(x))

# x'in elemanlarının kareköklerinden oluşan bir array oluşturduk.

[1.         1.         2.82842712 1.41421356 3.        ]


In [22]:
print(np.power(x, 3))

# x'in elemanlarının küpünden oluşan bir array oluşturduk.

[  1   1 512   8 729]


In [21]:
print(np.exp(x))

# x'in elemanlarının e^x halini yani doğal logaritmik hallerinden bir array oluşturduk.

[2.71828183e+00 2.71828183e+00 2.98095799e+03 7.38905610e+00
 8.10308393e+03]


In [23]:
print(np.sum(x))

# x'in elemanlarının toplamını aldık.

21


In [24]:
x = np.random.randint(1, 10, size= 9).reshape(3, 3)

print(x)

[[2 2 4]
 [6 2 5]
 [5 6 8]]


In [25]:
print(np.sum(x))

# Çok boyutlu arraylarda da aynı şekilde toplama işlemi yapabiliyoruz.

40


In [26]:
print(x.sum(axis= 0))

# x'in sütunlarının toplamını ayrı ayrı alabiliyoruz.

[13 10 17]


In [27]:
print(x.sum(axis= 1))

# x'in satırlarının toplamını ayrı ayrı alabiliyoruz.

[ 8 13 19]


In [28]:
print(x.min())

# En küçük elemanı bulabiliyoruz.

2


In [29]:
print(x.max())

# En büyük elemanı bulabiliyoruz.

8


In [30]:
print(x.argmin())

# En küçük elemanın index sayısını bulabiliyoruz.

0


In [31]:
print(x.argmax())

# En büyük elemanın index sayısını bulabiliyoruz.

8
