In [1]:
import numpy as np

x = np.array([3, 9, 8])

print(x)
print(type(x))

# Bu yöntemle küçük boyutlu ndarrayleri oluşturmak mümkün ancak büyük boyutlular için farklı bir yöntem kullanıyoruz.

[3 9 8]
<class 'numpy.ndarray'>


In [2]:
# np.zeros ve np.ones

x1 = np.zeros(4)

print(x1)

x2 = np.ones(4)

print(x2)

# np.zeros ile 0'lardan oluşan bir array, np.ones ile de 1'lerden oluşan array oluşturabiliyoruz.

[0. 0. 0. 0.]
[1. 1. 1. 1.]


In [3]:
print(x1.dtype)
print(x2.dtype)

# zeros ve ones bize float64 veri tipi gönderir.

float64
float64


In [4]:
y1 = np.zeros((2, 3, 4), dtype= np.int32)

print(y1)
print(y1.dtype)

# Girdiğimiz parametrelere bakacak olursak 
# (2, 3, 4) = 2 adet 3 satırlı 4 sütunlu matrisleri int32 veri tipiyle oluşturmasını istedik.

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
int32


In [5]:
y2 = np.ones((3, 2))

print(y2)

# Aynılarını ones içinde kullanabiliriz.

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
# np.full()

x = np.full((2, 3), 10)

print(x)
print(x.dtype)

# zeros ve ones'tan farklı olarak full() metodu ile sabit bir değerle matris oluşturabiliriz.
# Biz veri tipini ne girersek data type'ta o şekilde gerçekleşir.

[[10 10 10]
 [10 10 10]]
int32


In [8]:
x = np.full((2, 3), 10.0)

print(x)
print(x.dtype)

# Burada da görebiliriz. Float girdiğimiz için float64 çıktısı aldık.

[[10. 10. 10.]
 [10. 10. 10.]]
float64


In [9]:
y = 10.0 * np.ones((2,3))
z = 10.0 + np.zeros((2,3))

print(y)
print(z)

# Bu şekilde de full'de yapacağımız işlemleri yaparak aynı sonuca ulaşabiliriz..

[[10. 10. 10.]
 [10. 10. 10.]]
[[10. 10. 10.]
 [10. 10. 10.]]


In [11]:
# np.empty()

x = np.empty((2,2))

print(x)

# Burada görülen değerler keyfi değerlerdir. Aslında arrayimiz boştur.

[[1. 1.]
 [1. 1.]]


In [12]:
x.fill(3)

print(x)

# fill() metoduyla empty array'imizi doldurabiliriz.

[[3. 3.]
 [3. 3.]]


In [14]:
# np.eye()
# Birim matris oluşturmamızı sağlar.

x = np.eye(4)

print(x)

# İkinci bir parametre girmedik çünkü birim matrisler kare olmak zorundadır.
# Birim matris diyagonal elemanları 1 , diğer elemanları 0 olan matristir.

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
y = np.eye(5, 4)

print(y)

# Kare matris vermezseniz son satırdaki hata oluşur ve istediğimiz birim matrise ulaşamayız.

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [22]:
x = np.eye(6)

print(x)

print()

y = np.eye(6, k= 1)

print(y)

print()

z = np.eye(6, k= -2)

print(z)

# k değerinin ne işe yaradığını bu örneklerle görebilirsiniz.
# Pozitif girdiğimizde birim matrisin başlangıcını sağa doğru kaydırır.
# Negatif girdiğimizde birim matrisin başlangıcını aşağı doğru kaydırır.

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [23]:
x = np.identity(5)

print(x)

# identity() metoduyla da birim matris oluşturulabilir.

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [24]:
# np.diag()

x = np.diag([4, 7, 11, 3])

print(x)

# Verdiğimiz elemanları diyagonal olarak yerleştirir.

[[ 4  0  0  0]
 [ 0  7  0  0]
 [ 0  0 11  0]
 [ 0  0  0  3]]
