In [2]:
# Terminal ekranında pip install numpy yazarak kütüphaneyi yükleyebilirsiniz.

import numpy

dizi = numpy.array(["A","B","C","D"])
print(dizi)
type(dizi)

['A' 'B' 'C' 'D']


numpy.ndarray

In [3]:
# numpy genellikle np ile kullanılır onun için bu içe aktarma yöntemini kullandık.

import numpy as np

dizi = np.array(["A","B","C","D"])
print(dizi)
type(dizi)

['A' 'B' 'C' 'D']


numpy.ndarray

In [4]:
#  list, tuple, set, dict gibi bir dizi benzeri nesne ndarray'a dönüştürülebilir.
tuple_dizi = np.array((34,45,56,3))

print(tuple_dizi)
type(tuple_dizi)

[34 45 56  3]


numpy.ndarray

In [15]:
# O-D Diziler
# Tek elemanı olur.

dizi = np.array(57)

print(dizi)

57


In [11]:
# 1-D Diziler
# Dizi elemanları 0-D olan dizilere 1-D diziler denir.

dizi1d = np.array([2,4,6,8,10])
print(dizi1d)

[ 2  4  6  8 10]


In [12]:
# 2-D Diziler
# Dizi elemanları 1-D olan dizilere 2-D diziler denir.
# Matrisleri ve tensörleri ifade etmek için kullanılırlar.

dizi2d = np.array([[2,4,6,8,10],[1,3,5,7,9]])
print(dizi2d)

[[ 2  4  6  8 10]
 [ 1  3  5  7  9]]


In [13]:
# 3-D Diziler
# Dizi elemanları 2-D olan dizilere 3-D diziler denir.
# Genellikler üçüncü derece tensörleri ifade etmek için kullanılırlar.

dizi3d = np.array([[[2,4,6,8,10],[1,3,5,7,9]],[[2,4,6,8,10],[1,3,5,7,9]]])
print(dizi3d)

[[[ 2  4  6  8 10]
  [ 1  3  5  7  9]]

 [[ 2  4  6  8 10]
  [ 1  3  5  7  9]]]


In [16]:
# ndim özelliği ile bir dizinin kaç boyuta sahip olduğunu öğrenebilirsiniz.

print(dizi.ndim)
print(dizi1d.ndim)
print(dizi2d.ndim)
print(dizi3d.ndim)

0
1
2
3


In [17]:
# ndmin özelliği ile boyut sayısı tanımlanabilir.

dizi6d = np.array([1,2,3,4,5],ndmin = 6)

print(dizi6d)
print("Boyut sayısı:", dizi6d.ndim)

[[[[[[1 2 3 4 5]]]]]]
Boyut sayısı: 6


In [4]:
# Dizi elemanlarına erişmek
import numpy as np

dizi = np.array([1,3,5,7,9])

print(dizi[0]) # Diziler 0'ıncı değerden başlar
print(dizi[1])
print(dizi[2])
print(dizi[3])
print(dizi[4])

1
3
5
7
9


In [5]:
# 2 Boyutlu Dizilere Erişim
# Dizi numarası ve eleman numarasını virgülle ayırarak belirtiyoruz.

dizi = np.array([[1,3,5,7,9],[2,4,6,8,10]])

print(dizi[0,0])
print(dizi[1,4])
print(dizi[0,2])
print(dizi[1,3])

1
10
5
8


In [7]:
# 3-D Dizilere Erişim

dizi = np.array([[[1,3,5,7,9],[2,4,6,8,10]],[[11,13,15,17,19],[12,14,16,18,20]]])

print(dizi[0,1,2])

# printten sonra belirttiğimiz 0 değeri 2-D dizilerdeki boyutlara bakar ve [[1,3,5,7,9],[2,4,6,8,10]] erişir
# sonraki 1 sayısı 1-D dizilerdeki boyutlara bakar ve [2,4,6,8,10] erişir
# sonraki 2 sayısı 0-D dizilerdeki boyutlara bakar ve 6 sayısına erişir.

6


In [8]:
print(dizi[0,0,3])

7


In [9]:
print(dizi[0,1,3])

8


In [10]:
print(dizi[1,1,0])

12


In [17]:
# Negatif İndeksleme

# Dizilere sondan erişmekte mümkündür.

dizi = np.array([[1,3,5,7,9],[2,4,6,8,10]])

print(dizi[0,-5])
print(dizi[1,-1])
print(dizi[0,-3])
print(dizi[-1,-5])
print(dizi[-1,1])

1
10
5
2
4


In [18]:
print(dizi[-2,-2])

7


In [19]:
print(dizi[-1,-2])

8


In [23]:
# Numpy Slicing

dizi = np.array([1,2,3,4,5,6,7,8,9,10])

print(dizi[0:5])
print(dizi[:5])
print(dizi[0:-5])

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [24]:
print(dizi[5:])

[ 6  7  8  9 10]


In [25]:
# Slicing işleminde 3. bir parametrede vardır. Sayıları atlayarak almanızı sağlar.

print(dizi[::2])

[1 3 5 7 9]


In [26]:
# 2-D diziler için Slicing

dizi = np.array([[1,3,5,7,9],[2,4,6,8,10]])

print(dizi[1,1:4])

[4 6 8]


In [27]:
print(dizi[0:2,2])

# Her iki diziden de 3. elemanı almış olduk.

[5 6]


In [28]:
print(dizi[0:2,1:4])

# Her iki diziden de 2. elemandan 5.elemana kadar olan kısmı aldık

[[3 5 7]
 [4 6 8]]


In [7]:
import numpy as np
a = np.array([1,3,5,7,9])
b = np.array([2,4,6,8,10])

a*b

array([ 2, 12, 30, 56, 90])