In [1]:
import numpy as np

x = np.array([2, 5, 3, 6, 9])
y = np.array([6, 1, 8, 7, 3])

print(np.intersect1d(x, y))

# İki array arasında ortak olan elemanları yazdırdık.

[3 6]


In [2]:
z = np.intersect1d(x, y)

print(type(z))

# Gördüğünüz gibi z'nin de tipi ndarray.

<class 'numpy.ndarray'>


In [3]:
print(np.setdiff1d(x, y))

# x'te olup y'de olmayan elemanları yazdırdık.

[2 5 9]


In [4]:
print(np.setdiff1d(y, x))

# y'de olup x'de olmayan elemanları yazdırdık.

[1 7 8]


In [5]:
print(np.union1d(x, y))

# x ve y'nin birleşimini yazdırdık.

[1 2 3 5 6 7 8 9]


In [6]:
print(np.in1d(x, y))

# x'teki elemanların y'de olup olmamasını sorgular. Varsa True yoksa False değeri yazdırılır.

[False False  True  True False]


In [7]:
print(np.in1d(y, x))

# Bu da tam tersi.

[ True False False False  True]


In [8]:
x = np.array([2, 5, 3, 6, 9, 4, 3, 6, 5, 0])

print(np.unique(x))

# Kendi içindeki elemanları gözden geçirir ve tekrar edenleri tekrardan yazmaz.
# Sadece bir kere yazmakla yetinir.

[0 2 3 4 5 6 9]


In [10]:
# sort()

x = np.random.randint(1, 10, size= 10)

print(x)

[5 1 1 7 2 7 8 6 8 7]


In [11]:
print(np.sort(x))

# x'in içindeki elemanları küçükten büyüğe sıraladık.

[1 1 2 5 6 7 7 7 8 8]


In [12]:
print(x)

# Ancak bu sıralama kalıcı bir şekilde gerçekleşmez. Orjinal aynı şekilde kalır.

[5 1 1 7 2 7 8 6 8 7]


In [13]:
y = np.random.randint(1, 10, size= 10)

print(y)

[1 9 9 2 7 4 8 6 9 1]


In [15]:
y.sort()

print(y)

# sort'u bu şekilde kullanırsak y'nin orjinali de değişmiş olur.

[1 1 2 4 6 7 8 9 9 9]


In [16]:
x = np.random.randint(1, 10, size= (5,5))

print(x)

[[3 2 9 6 3]
 [7 4 5 2 5]
 [1 4 2 6 4]
 [5 2 8 8 2]
 [5 4 3 6 5]]


In [17]:
print(np.sort(x, axis= 0))

# axis= 0 yaptığımızda küçükten büyüğe sütunlara göre sıraladı. Yukarıdan aşağıya.

[[1 2 2 2 2]
 [3 2 3 6 3]
 [5 4 5 6 4]
 [5 4 8 6 5]
 [7 4 9 8 5]]


In [19]:
print(np.sort(x, axis= 1))

# axis= 1 yaptığımızda küçükten büyüğe satırlara göre sıraladı. Soldan sağa.

[[2 3 3 6 9]
 [2 4 5 5 7]
 [1 2 4 4 6]
 [2 2 5 8 8]
 [3 4 5 5 6]]
