In [1]:
import numpy as np

In [3]:
# 5 elemanlı 0 ve 1'lerden oluşan ndarrayleri oluşturunuz.

x = np.zeros(5)

print(x)

[0. 0. 0. 0. 0.]


In [4]:
y = np.ones(5)

print(y)

[1. 1. 1. 1. 1.]


In [6]:
# 7 ve 41 dahil olmak üzere aralarındaki tek sayıları gösteren ndarrayleri oluşturunuz.

x = np.arange(7, 42, 2)

print(x)

[ 7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41]


In [7]:
# 1 ile 10 arasında rastgele 16 elemandan oluşan 4*4'lük bir matris oluşturunuz.

x = np.random.randint(1, 10, size= 16).reshape(4, 4)

print(x)

[[5 4 9 3]
 [2 9 3 8]
 [9 1 6 6]
 [5 4 2 8]]


In [10]:
# 0.1 ile 1 arasında eşit farklı 10 elemanlı ndarrayleri oluşturunuz.

x = np.linspace(0.1, 1, num= 10)

print(x)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [13]:
# 0'dan 25'e kadar elemanı olan 24 elemanlı 5*5'lik x matrisinden 7,8,12,13 sayılarını yazdırınız.

x = np.arange(0, 25).reshape(5, 5)

print(x)
print()

y = x[1:3, 2:4]

print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 7  8]
 [12 13]]


In [17]:
# Elemanları 1 ile 17 arasındaki sayılardan oluşan 4*4'lük x matrisindeki çift sayıları Boolean 2*4'lük y matrisine dönüştürün.

x = np.arange(1, 17).reshape(4, 4)

print(x)
print()

y = x[x % 2 == 0]
y = y.reshape(2, 4)

print(y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 2  4  6  8]
 [10 12 14 16]]


In [25]:
# Sinemaya giriş ücreti öğrenciler için 5tl, olmayanlar için 10tl olan bir sinemada 100 kişi için 700tl toplandığına göre 
# öğrenci sayısı kaçtır?

a = np.array([[1, 1], [5, 10]])
print(a)
print()

b = np.array([100, 700])

print(b)
print()

x = np.linalg.solve(a, b)

print(f"Öğrencilerin sayısı: {x[0]}, Öğrenci olmayanların sayısı: {x[1]}")

[[ 1  1]
 [ 5 10]]

[100 700]

Öğrencilerin sayısı: 60.0, Öğrenci olmayanların sayısı: 40.0


In [26]:
# Tek boyutlu ve çift boyutlu Ndarrayler için skaler çarpım örnekleri gösteriniz.

x = np.random.randint(1, 5, 4)
print(x)
print()

y = np.random.randint(1, 5, 4)
print(y)
print()

print(np.dot(x, y))

[4 1 2 3]

[3 2 4 4]

34


In [27]:
x = np.random.randint(1, 5, 6).reshape(3, 2)
print(x)
print()

y = np.random.randint(1, 5, 6).reshape(2, 3)
print(y)
print()

print(np.dot(x, y))

[[1 1]
 [2 1]
 [4 1]]

[[4 4 4]
 [3 1 2]]

[[ 7  5  6]
 [11  9 10]
 [19 17 18]]
