In [1]:
import numpy as np

x = np.random.randint(1, 10, size= 8)

print(x)

[4 6 2 5 1 3 7 3]


In [2]:
print(x.mean())

# Array'imiz elemanlarının ortalamasını bulduk.

3.875


In [3]:
print(np.median(x))

# Elemanlar sıralandıktan sonra ortada eleman varsa onu yoksa ortada kalan iki elemanın ortalamasını bulduk.

3.5


In [4]:
print(x.std())

# x array'ının standart sapmasını bulduk.

1.899835519196333


In [6]:
x = np.random.randint(1, 10, size= (4, 3))

print(x)

[[4 1 7]
 [2 3 5]
 [4 9 2]
 [2 7 6]]


In [7]:
print(x.mean(axis= 0))

# x arrayının sütunlarının ortalamasını ayrı ayrı öğrenebiliriz.

[3. 5. 5.]


In [8]:
print(x.mean(axis= 1))

# x arrayının satırlarının ortalamasını ayrı ayrı öğrenebiliriz.

[4.         3.33333333 5.         5.        ]


In [9]:
print(np.median(x, axis= 1))

# x arrayının satırlarının ortasındaki sayıları öğrenebiliriz. 
# Veya tam ortada sayı yoksa ortada kalan 2 sayının ortalamasını öğrenebiliriz.

[4. 3. 4. 6.]


In [11]:
print(x.std(axis= 0))

# x arrayının sütunlarının standart sapmasını ayrı ayrı öğrenebiliriz.

[1.         3.16227766 1.87082869]


In [12]:
x = np.random.randint(1, 10, size= (3, 2))
y = np.random.randint(1, 10, size= (3, 2))

print(x)
print()
print(y)

[[5 4]
 [7 5]
 [2 5]]

[[8 8]
 [8 1]
 [3 6]]


In [13]:
print(x + y)

# Şekli aynı olan matrislerde işlem yapmakta hiçbir sorun olmuyor. Bunlara da element-wise denir.

[[13 12]
 [15  6]
 [ 5 11]]


In [14]:
# broadcastable

# Şekli aynı olmayan matrislerin birbirine benzetilip öyle işleme sokulmasına dayanan bir sistemdir.

x = np.random.randint(1, 10, size= 1)
y = np.random.randint(1, 10, size= (3, 2))

print(x)
print()
print(y)

[1]

[[3 5]
 [9 9]
 [4 5]]


In [15]:
print(x + y)

# Bu iki matrisin broadcastable olduğunu toplama işleminin yapılabilmesiyle görmüş olduk.

[[ 4  6]
 [10 10]
 [ 5  6]]


In [16]:
x = np.random.randint(1, 10, size= 2)

print(x)

[7 3]


In [17]:
print(x + y)

# Bu da aynı şekilde broadcastable çünkü x matrisi genişletilerek y'ye benzetilebilir.

[[10  8]
 [16 12]
 [11  8]]


In [18]:
x = np.random.randint(1, 10, size= 3)

print(x)

[3 3 2]


In [19]:
print(x + y)

# Bu sefer işlem olmadı çünkü 3 satırlı olan x hiçbir genişletilme yaparak y'ye benzetilemiyor.

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [20]:
x = np.random.randint(1, 10, size= (1, 3))
y = np.random.randint(1, 10, size= (3, 1))

print(x)
print()
print(y)

[[1 9 9]]

[[9]
 [9]
 [8]]


In [21]:
print(x + y)

# Yine genişletilerek birbirine benzetilebildiği için bunlarada broadcastable diyebiliriz.
# Daha detaylı bilgi için internetten görsel aramalarına bakmanızı tavsiye ederim.
# Broadcastable matrislerde bu işlem yaptıktan sonra satır ve sütunlara erişebilmemiz sayesinde istediğimiz sonuçları elde edebiliyoruz.

[[10 18 18]
 [10 18 18]
 [ 9 17 17]]
