In [1]:
import numpy as np

x = np.arange(5)

print(x)

[0 1 2 3 4]


In [2]:
print(x[0])

# index numarasıyla istediğimiz elemana ulaşabiliriz.

0


In [3]:
print(x[2])

2


In [5]:
print(x[4])

4


In [6]:
print(x[-1])

# Negatif indeks numaralarıyla da ulaşılabilir.

4


In [7]:
print(x[-2])

3


In [8]:
print(x[-5])

0


In [10]:
x = np.arange(5)

print(x)

x[2] = 200

print(x)

# İndex numarası ile elemanları bu şekilde değiştirebiliyoruz.

[0 1 2 3 4]
[  0   1 200   3   4]


In [12]:
x = np.arange(12).reshape(3, 4)

print(x)

print(x[0, 0])

# 2 boyutlu arraylerde eleman sayısına bu şekilde ulaşılır.
# [0, 0] = 0. satırın 0. sütunu demektir.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0


In [13]:
print(x[1, 2])

# [1, 2] = 1. satır 2. sütun

6


In [14]:
x[0, 0] = 100

print(x)

# Aynı şekilde değişimde yapılabilir.

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [16]:
x = np.arange(6)

print(x)

y = np.delete(x, [0, 1])

print(y)
print(x)

# y'de yaptığımız işlemle x'in 0 ve 1'inci elemanlarını sildik ve yeni bir tanıma atadık.
# Gördüğünüz gibi x değişmedi.
# Ancak y'de elemanlar silindi ve öyle çıktı alındı.

[0 1 2 3 4 5]
[2 3 4 5]
[0 1 2 3 4 5]


In [18]:
# axis = 0 row - satır
# axis = 1 column - sütun

x = np.arange(16).reshape(4, 4)

print(x)
print()

x = np.delete(x, 1, axis= 0)

print(x)

# axis=0 girdiğimiz için silinen 2. parametre belirttiğimiz 1. satır oldu.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]


In [19]:
x = np.delete(x, [0, 2], axis= 1)
print(x)

# axis=1 dediğimiz için 2. parametrede girdiğimiz 0 ve 2. sütunlar silindi.

[[ 1  3]
 [ 9 11]
 [13 15]]


In [20]:
# np.append()

x = np.arange(5)

print(x)
print()

x = np.append(x, 100)

print(x)

# 100 değerini x array'inin sonuna ekledik.

[0 1 2 3 4]

[  0   1   2   3   4 100]


In [21]:
x = np.append(x, [200, 300])

print(x)

[  0   1   2   3   4 100 200 300]


In [23]:
x = np.arange(9).reshape(3, 3)

print(x)
print()

x = np.append(x, [[100, 200, 300]], axis= 0)

print(x)

# axis ile satır olarak ekleyeceğimizi belirttik.
# Matrise uygun bir array girdik.
# Ve neye ekleceğimizi belirttik. İşte sonuç

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[  0   1   2]
 [  3   4   5]
 [  6   7   8]
 [100 200 300]]


In [25]:
x = np.append(x, [[400], [500], [600], [700]], axis= 1)

print(x)

# Burada farklı olarak bütün elemanları 2 boyutlu bir array içine değilde
# Hepsini ayrı ayrı 2 boyutlu arrayler olacak biçiminde yazdık.
# Ayrıca axis'i de 1 girerek sütun olduğunu belirttik.

[[  0   1   2 400]
 [  3   4   5 500]
 [  6   7   8 600]
 [100 200 300 700]]


In [26]:
# np.insert()

x = np.arange(5)

print(x)
print()

x = np.insert(x, 0, 10)

print(x)

# İlk parametre olarak hangi arrayde işlem yapılacağı,
# İkinci olarak hangi index'e eleman ekleneceği,
# Üçüncü olarakta eklemek istediğimiz parametreyi giriyoruz.
# Girdiğimiz index numarasından sağa açılarak yeni elemana yer açar ve eklenir.

[0 1 2 3 4]

[10  0  1  2  3  4]


In [27]:
x = np.insert(x, 0, [20, 30])

print(x)

# Birden fazla elemanda eklenebilir.

[20 30 10  0  1  2  3  4]


In [33]:
x = np.arange(9).reshape(3, 3)

print(x)
print()

x = np.insert(x, 1, [100, 200, 300], axis= 0)

print(x)

# Matrise uygun şekilde elemanlar eklenmelidir. 3 sütunlu olduğu için bizde parametre olarak 3 sütunlu array yazdık.
# Farklı olarak axis kullandık. axis= 0 parametresiyle satır olarak ekleyeceğimizi belirttik.

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[  0   1   2]
 [100 200 300]
 [  3   4   5]
 [  6   7   8]]


In [34]:
x = np.insert(x, 0, [400, 500, 600, 700], axis= 1)

print(x)

# axis=1 kullanarak sütun olarak eklemek istediğimizi belirttik.
# Yine matrise uygun sayıda eleman girdik. İşte sonuç.
# append'ten farklı olarak elemanları tek tek farklı arraylerde belirtmedik. Tek arrayde hepsini belirtebildik.

[[400   0   1   2]
 [500 100 200 300]
 [600   3   4   5]
 [700   6   7   8]]


In [35]:
# np.stack()

x = np.arange(3)

print(x)
print()

y = np.arange(9).reshape(3, 3)

print(y)
print()

z = np.vstack((x, y))

print(z)

# vstack yani vertical stack gördüğünüz gibi x'i y'ye satır olarak ekledi.

[0 1 2]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2]
 [0 1 2]
 [3 4 5]
 [6 7 8]]


In [36]:
a = np.hstack((x, y))

print(a)

# hstack yani horizontal stack x'i y'ye sütun olarak ekler.
# Ancak hata alırız çünkü matrislerin sütunları birbirine eşit değildir.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [40]:
y = y.reshape(9)

print(y)
print()

a = np.hstack((x, y))

print(a)

# Hatayı düzeltmek için şekil değiştirme uyguladık.
# 9 elemanlı ve 2 boyutlu olan y'yi x'e benzetmek için reshape ile 1 boyutlu hale getirdik.
# Daha sonra ekleme işlemini uygulayınca düzgün bir şekilde ekleme yapıldı.

[0 1 2 3 4 5 6 7 8]

[0 1 2 0 1 2 3 4 5 6 7 8]
