In [1]:
import numpy as np

x = np.array([3, 4.0, 5])

print(x)
print(x.dtype)

# Bir adet float değerimiz olduğu için dtype ile float64 çıktısını aldık. 
# Bütün elemanlar float64'e dönüştürüldü.

[3. 4. 5.]
float64


In [2]:
# 5 temel sayı veri tipimiz var.
# Bunlar bool, int, float, complex, uint'dir.

x = np.array([3, 4, 5])

print(x)
print(x.dtype)

[3 4 5]
int32


In [4]:
y = np.array([3, 4.0, 5], dtype= np.int32)

print(y)
print(y.dtype)

z = np.array([3, 4.0, 5], dtype= np.float64)

print(z)
print(z.dtype)

a = np.array([3, 4.0, 5], dtype= np.complex128)

print(a)
print(a.dtype)

# Kendimizde bu şekilde data tipini belirleyebiliyoruz.

[3 4 5]
int32
[3. 4. 5.]
float64
[3.+0.j 4.+0.j 5.+0.j]
complex128


In [5]:
x = np.array([1.2, 2.7, 3.8], dtype=np.int32)

print(x)
print(x.dtype)

# Birbirleri arasındaki dönüşümlerin nasıl olduğunu bilmek gerekiyor. 
# Aksi takdirde yanlış sonuçlar alabiliriz.
# Bu yaptığımız işleme de downcast adı verilir. Detaylı bilgiye internetten ulaşabilirsiniz.

[1 2 3]
int32


In [7]:
x = np.array([1, 2, 3, 4], dtype= np.float64)

print(x)
print(x.dtype)

x = np.array(x, dtype= np.complex128)

print(x)
print(x.dtype)

# Verileri tekrar girmeden de üzerinde bu şekilde değişiklik yapabiliriz.

[1. 2. 3. 4.]
float64
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128


In [8]:
x = np.array([1,2,3,4], dtype= np.float64)

x = x.astype(np.complex128)

print(x)
print(x.dtype)

# Aynı değişimi astype() metodu ile de değiştirebiliriz.

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
complex128


In [15]:
x1 = np.array([1, 2, 3], dtype= np.int32)
x2 = np.array([5.2, 2.8, 4.9], dtype= np.float64)

print(x1 + x2)
print((x1 + x2).dtype)

# İki array'i işleme soktuğumuzda her zaman aldığımız sonuç daha yüksek olan veri tipi biçiminde yazdırılır.

[6.2 4.8 7.9]
float64


In [16]:
x = np.sqrt(np.array([-1, 9, 4], dtype= np.float64))

print(x)
print(x.dtype)

# sqrt() metodu karekök almayı sağlar.
# Burada aldığımız hatanın sebebi -1 sayısının karekökünün bir complex sayı olmasıdır.
# Biz float64 değeri girerek burada hata yaptık.

[nan  3.  2.]
float64


C:\Users\Fallrytme\AppData\Local\Temp\ipykernel_4940\1006470939.py:1: RuntimeWarning: invalid value encountered in sqrt
  x = np.sqrt(np.array([-1, 9, 4], dtype= np.float64))


In [17]:
x = np.sqrt(np.array([-1, 9, 4], dtype= np.complex128))

print(x)
print(x.dtype)

# Eğer doğru şekilde complex128 girersek bu hatayı almayız.

[0.+1.j 3.+0.j 2.+0.j]
complex128


In [20]:
print(x.real)
print(x.imag)

print((x.real).dtype)
print((x.imag).dtype)

# real ve imag metodları ile de complex sayının reel ve sanal kısımlarını ayrı ayrı alabiliriz.

[0. 3. 2.]
[1. 0. 0.]
float64
float64


In [21]:
x = np.array([5, 9, 3.2, 16])
np.save("ndarray_1", x)

# save() metoduyla array'imizi kaydedebiliriz.

In [22]:
y = np.load("ndarray_1.npy")

print(y)
print(y.shape)

# load() metoduyla kaydettiğimiz array'imizi kullanabiliriz.

[ 5.   9.   3.2 16. ]
(4,)
