In [2]:
import numpy as np

# 1'den 10'a kadar bir Numpy dizisi oluşturun

x = np.array([1,2,3,4,5,6,7,8,9,10])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
# 2 boyutlu bir Numpy dizisi oluşturun

x = np.array([[1,3,5,7,9],[2,4,6,8,10]])
x

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [7]:
# Boyutları 2x3 olan bir Numpy dizisinin satır sayısını bulun

x = np.array([[1,2,3],[4,5,6]])
print(x.shape[0])

2


In [8]:
# Boyutları 2x3 olan bir Numpy dizisinin sütun sayısını bulun

print(x.shape[1])

3


In [11]:
# Bir Numpy dizisindeki en büyük değeri bulun

x = np.array([1,2,3,4,5,6,7,8,9,10])
print(x.max())

10


In [12]:
# Bir Numpy dizisindeki en küçük değeri bulun

print(x.min())

1


In [13]:
# Bir Numpy dizisindeki ortalamayı bulun

print(x.mean())

5.5


In [14]:
# Bir Numpy dizisindeki standart sapmayı bulun

print(x.std())

2.8722813232690143


In [7]:
# Bir Numpy dizisinde tekrar eden elemanları bulun

x = np.array([1,1,2,3,4,5,5,5,6,7,7,8,9,9,9,10])
a = 0
b = []
while a < len(x):
    y = np.where(x == x[a])
    if len(y[0]) > 1:
        if not x[a] in b:
            b.append(x[a])
    a += 1
print(b)

(array([0, 1], dtype=int64),)
(array([0, 1], dtype=int64),)
(array([2], dtype=int64),)
(array([3], dtype=int64),)
(array([4], dtype=int64),)
(array([5, 6, 7], dtype=int64),)
(array([5, 6, 7], dtype=int64),)
(array([5, 6, 7], dtype=int64),)
(array([8], dtype=int64),)
(array([ 9, 10], dtype=int64),)
(array([ 9, 10], dtype=int64),)
(array([11], dtype=int64),)
(array([12, 13, 14], dtype=int64),)
(array([12, 13, 14], dtype=int64),)
(array([12, 13, 14], dtype=int64),)
(array([15], dtype=int64),)
[1, 5, 7, 9]


In [50]:
# 2 boyutlu bir Numpy dizisindeki tüm elemanların toplamını bulun

x = np.array([[1,3,5,7,9],[2,4,6,8,10]])

y = x.sum()
print(y)

55


In [55]:
# 2 boyutlu bir Numpy dizisindeki her bir satırdaki elemanların toplamını bulun

x = np.array([[1,3,5,7,9],[2,4,6,8,10]])

y = x[0].sum()
z = x[1].sum()

print(y)
print(z)

25
30


In [61]:
# 2 boyutlu bir Numpy dizisindeki her bir sütundaki elemanların toplamını bulun

x = np.array([[1,3,5,7,9],[2,4,6,8,10]])

y = x[:,0:1].sum()
z = x[:,1:2].sum()
a = x[:,2:3].sum()
b = x[:,3:4].sum()
c = x[:,4:5].sum()

print(y)
print(z)
print(a)
print(b)
print(c)

3
7
11
15
19


In [67]:
# Numpy dizisi boyutlarını değiştirin

x = np.array([[1,3,5,7,9],[2,4,6,8,10]])

print(x.reshape(5,2))

[[ 1  3]
 [ 5  7]
 [ 9  2]
 [ 4  6]
 [ 8 10]]


In [69]:
# Numpy dizisindeki elemanların transpozunu alın

x = np.array([[1,3,5,7,9],[2,4,6,8,10]])

print(x)
print(x.T)

[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [70]:
# Numpy dizisindeki elemanların sıralamasını yapın

x = np.array([[5,7,3,4,2],[6,4,8,1,6]])

print(np.sort(x))

[[2 3 4 5 7]
 [1 4 6 6 8]]


In [71]:
# 2 boyutlu bir Numpy dizisindeki her bir sütundaki elemanların ortalamasını bulun

x = np.array([[1,3,5,7,9],[2,4,6,8,10]])

y = x[:,0:1].mean()
z = x[:,1:2].mean()
a = x[:,2:3].mean()
b = x[:,3:4].mean()
c = x[:,4:5].mean()

print(y)
print(z)
print(a)
print(b)
print(c)

1.5
3.5
5.5
7.5
9.5


In [73]:
# 2 boyutlu bir Numpy dizisindeki her bir satırdaki elemanların standart sapmasını bulun

x = np.array([[1,3,5,7,9],[2,4,6,8,10]])

y = x[0].std()
z = x[1].std()

print(y)
print(z)

2.8284271247461903
2.8284271247461903


In [80]:
# 2 boyutlu bir Numpy dizisinde belirli bir elemanın index değerini bulun

x = np.array([[1,3,5,7,9],[2,4,6,8,10]])

y = np.where(x == 5)
print(f"Bulunduğu satır: {y[0]}, Bulunduğu sütun: {y[1]}")

Bulunduğu satır: [0], Bulunduğu sütun: [2]


In [81]:
# 2 boyutlu bir Numpy dizisinde belirli bir sütunu seçin

x = np.array([[1,3,5,7,9],[2,4,6,8,10]])

print(x[:,2])

[5 6]


In [82]:
# 2 boyutlu bir Numpy dizisinde belirli bir satırı seçin

x = np.array([[1,3,5,7,9],[2,4,6,8,10]])

print(x[1])

[ 2  4  6  8 10]
