In [2]:
import numpy as np

x = np.arange(10)

print(x)
print()

print(x[2:6])

# 2. elemandan 6. elemana kadar slicing yapmış olduk. 6. eleman dahil olmuyor.

[0 1 2 3 4 5 6 7 8 9]

[2 3 4 5]


In [4]:
print(x[4:])

# Bitiş noktası belirtmediğimiz için 4. elemandan sonuna kadar yazdırdı.

[4 5 6 7 8 9]


In [5]:
print(x[:7])

# Başlangıç noktası belirtmediğimiz için baştan 7. elemana kadar yazdırdı.

[0 1 2 3 4 5 6]


In [6]:
print(x[::-1])

# 3. parametrede sayıları hangi aralıkla alınması gerektiğini gösterir.
# Burada -1 diyerek - sağdan sola doğru okumasını 1 ise 1 1 ilerlemesini sağladı. 
# Bu sayede ters yazabildik.

[9 8 7 6 5 4 3 2 1 0]


In [10]:
print(x[3:7:2])

[3 5]


In [7]:
print(x[:-1])

# Aynı dilimleme terstende gösterilebilir.

[0 1 2 3 4 5 6 7 8]


In [9]:
print(x[-4:-2])

[6 7]


In [13]:
x = np.arange(25).reshape(5, 5)

print(x)

# 5*5 2 boyutlu matrisi oluşturduk.

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [14]:
y = x[0:3, 1:4]

print(y)

# 0'dan 3. satıra kadar ve(,) 1'den 4. sütuna kadar yazdırdık.

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [15]:
z = x[2:]

print(z)

# Tek parametre verdiğimiz için ve bitiş değeri belirtmediğimiz için 2 ve 2 den sonraki tüm satırladı yazdırdık.

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [16]:
t = x[::]

print(t)

#  Tek parametre verdiğimiz için ve başlangıç, bitiş ve aralık değerleri belirtmediğimiz için hepsini yazdırdık.

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [17]:
v = x[:, 3:]
print(v)

# Satır için bir değer belirtilmediği için hepsini aldı.
# Ancak sütunlarda başlangıç değeri 3 olarak belirtildiği için 3 ve 3'ten sonraki bütün sütunlar yazdırıldı.

[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]]


In [18]:
x = np.arange(9).reshape(3, 3)

print(x)

# 3*3lük matris oluşturduk.

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
y = x[1:2, 0:2]

print(y)

# 1. satır ve 0,1. sütunları aldık ve yazdırdık.

[[3 4]]


In [22]:
y[0, 0] = 100

print(y)
print()
print(x)

# 0. satır, 0. sütundaki elemanı 100 ile değiştirdik.
# y'deki değişim x'te de etki etti.

[[100   4]]

[[  0   1   2]
 [100   4   5]
 [  6   7   8]]


In [23]:
print(np.shares_memory(x, y))

# Aldığımız True değeri aynı hafızayı kapladığını bize gösterdi.
# Yani slicing işlemi yaptıktan sonra elde ettiğimiz yeni tanımın bir elemanını değiştirirsek orjinalde de değişim olur.
# Buna çok DİKKAT etmemiz gerekiyor.

True


In [26]:
x = np.arange(16).reshape(4, 4)

print(x)
print()

y = np.copy(x[0:3, 1:3])

print(y)
print()

print(np.shares_memory(x, y))

# copy metodunu x'e slicing yaparak kullandık.
# copy metodunu kullandığımız için öncekine göre artık x ve y aynı hafızada yer tutmuyor.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 1  2]
 [ 5  6]
 [ 9 10]]

False


In [27]:
y[0,0]= 100

print(y)
print()
print(x)

# Gördüğünüz gibi copy metodu kullandığımızda y'de yaptığımız değişiklik x'te bir değişime sebep olmadı.

[[100   2]
 [  5   6]
 [  9  10]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [30]:
z = x[1:2, 1:2].copy()

print(z)
print()
print(np.shares_memory(x, z))

# copy metodunu bu şekilde de kullanabilirsiniz. Aynı sonucu aldığımızı görebilirsiniz.

[[5]]

False
