In [7]:
import numpy as np

# 4*2'lik matris oluşturun ve özelliklerini yazdırın.

x = np.arange(1, 9).reshape(4, 2)
print(x)

print(np.shape(x))
print(np.ndim(x))
print(x.size)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2
8


In [14]:
# Her öge arasında 10 fark olacak şekilde 100 ile 190 arasında bir 5*2'lik matris oluştur.

x = np.linspace(100, 190, num= 10).reshape(5, 2)

print(x)

[[100. 110.]
 [120. 130.]
 [140. 150.]
 [160. 170.]
 [180. 190.]]


In [15]:
# sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) bu array'daki her satırdan üçüncü sütunu yazdır.

sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray)
print()

x = sampleArray[:,2:]
print(x)

[[11 22 33]
 [44 55 66]
 [77 88 99]]

[[33]
 [66]
 [99]]


In [18]:
# Aşağıda verilen arraydan çift satıları ve tek sütunları yazdır.

sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print(sampleArray)
print()

x = sampleArray[0::2, 1::2]
print(x)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

[[ 6 12]
 [30 36]
 [54 60]]


In [20]:
# Aşağıda verilen iki arrayi önce toplayın sonra karelerini ekrana yazdırın.

arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
print(arrayOne)
print()
print(arrayTwo)
print()

toplam = arrayOne + arrayTwo
print(toplam)
print()

karesi = np.power(toplam, 2)
print(karesi)

[[ 5  6  9]
 [21 18 27]]

[[15 33 24]
 [ 4  7  1]]

[[20 39 33]
 [25 25 28]]

[[ 400 1521 1089]
 [ 625  625  784]]
