In [1]:
import numpy as np

In [2]:
x = np.linspace(1, 21, 11)

print(x)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]


In [3]:
y = np.array([2, 4, 7])

print(y)

[2 4 7]


In [4]:
print(x[y])

# x arrayinin y'inci elemanlarını bize göstermesini sağladık.
# 2, 4, 7. elemanlara ulaşmış olduk.

[ 5.  9. 15.]


In [5]:
x = np.arange(25).reshape(5, 5)

print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [6]:
y = np.array([1, 2])

print(y)

[1 2]


In [7]:
print(x[y, :])

# Bu sefer 2 boyutlu arraylerde arrayle slicing işlemi yapmış olduk.
# y'nin gösterdiği 1 ve 2. satırladı aldı sütun konusunda bir parametre girilmediği için hepsini aldı.

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [8]:
print(x[:, y])

# Bu seferde satırların tamamını alıp y'nin gösterdiği gibi sadece 1. ve 2. sütunları gösterdi.

[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]]


In [9]:
z = x[y,:]

print(z)

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [10]:
z[0,0]= 100

print(z)

[[100   6   7   8   9]
 [ 10  11  12  13  14]]


In [11]:
print(x)

# z'de yaptığımız değişiklik x'i etkilemedi.
# Buna fancy indexing deniyor. İnternettende detaylı bakabilirsiniz.

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [12]:
print(np.shares_memory(x, z))

# Gördüğünüz gibi False değerini bize döndürdü.

False


In [13]:
# boolean indexing

x = np.arange(10)

print(x)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
print(x[(x % 2 == 0)])

# Slicing ederken parantezin içine bu şekilde şartta koyabiliriz.
# True değer verenler ekrana yazdırılır.
# Burada 2'ye tam bölünenleri ekrana yazdırmış olduk.

[0 2 4 6 8]


In [16]:
z = x[(x % 2 == 0)]

print(z)

[0 2 4 6 8]


In [17]:
z[0]= 100

print(z)

[100   2   4   6   8]


In [18]:
print(x)

# x aynı fancy indexingte olduğu gibi z değişmesine rağmen x değişmedi.

[0 1 2 3 4 5 6 7 8 9]


In [19]:
print(np.shares_memory(x, z))

# Buradan aldığımız False değeriyle de bunu görebiliriz.

False


In [20]:
x = np.random.randint(10, size= 10)

y = np.random.randint(10, size= 10)

print(x)
print()
print(y)

[2 5 6 8 9 4 1 3 6 1]

[6 6 0 2 4 0 7 0 7 5]


In [21]:
print(x > y)

# Koşul sunduğumuzda bize geri döndürülen değerler bool veri tipinde olduğunu gördük.

[False False  True  True  True  True False  True False False]


In [22]:
print(type(x > y))

# Burada False ve True değerlerinin de veri tipinin ndarray olduğunu görebiliyoruz.

<class 'numpy.ndarray'>


In [23]:
print((x > y).dtype)

# ndarraylerin 5 ana veri tiplerinden biri de bool'du. Burada da bool veri tipiyle işlem yapabildiğimizi kanıtlamış olduk.

bool


In [24]:
print(np.all(x > y))

# np.all pythonda gördüğümüz and gibi çalışır.
# Yani x'in bütün değerleri y'den büyük olsaydı True dönerdi.

False


In [25]:
print(np.any(x > y))

# np.all pythonda gördüğümüz or gibi çalışır.
# Yani x'in bütün değerleri y'den küçük olsaydı False dönerdi.

True


In [26]:
x = np.linspace(1, 21, 11)

print(x)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21.]


In [27]:
mask = (x % 3 == 0)

print(mask)

[False  True False False  True False False  True False False  True]


In [28]:
print(type(mask))

<class 'numpy.ndarray'>


In [31]:
print(x[mask])

# Bu şekilde önce başka bir değere atama yapıp sonra x'in slicingi içinde kullanabilirsiniz.

[ 3.  9. 15. 21.]


In [32]:
x[mask] = -3

print(x)

# mask elemanlarının tamamı içinde aynı anda değiştirme yapmak için kullanılabilir.

[ 1. -3.  5.  7. -3. 11. 13. -3. 17. 19. -3.]
